name: Test App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  DATABASE_URL: postgresql://postgres:password1@localhost:5432/page_analyzer
  SECRET_KEY: $SECRET_KEY
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password1
          POSTGRES_DB: page_analyzer
    steps:
      - uses: actions/checkout@v3
      - name: set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref == 'refs/heads/main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true